### ISSUE TITLE
support for mac os?

### ISSUE THREAD

**Issue by Mangocod3r** [abhimanyutherobot/kmit-browser#1]
when will browser stable be released for mac os

**Comment by msripooja** [comment]
@Mangocod3r ,
BOSSS stable release for Mac OS will be rolled out soon. 
Follow this repo for KMIT BOSSS releases - https://github.com/abhimanyutherobot/kmit-bosss. The link to report issues has been updated in BOSSS v1.0.1. Please make sure to use latest version of BOSSS.
